// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Ipl6 = (function() {

    function Ipl6($container) {
      var _this = this;
      this.$container = $container;
      this.mouseDistFromCenterY = __bind(this.mouseDistFromCenterY, this);

      this.mouseDistFromCenterX = __bind(this.mouseDistFromCenterX, this);

      this.update = __bind(this.update, this);

      this.mouseX = 0;
      this.mouseY = 0;
      this.maxXRot = 35;
      this.maxYRot = 35;
      this.fps = 30;
      window.setInterval(this.update, 1000 / this.fps);
      $('body').css('-webkit-perspective', 1500);
      $(window).mousemove(function(e) {
        _this.mouseX = e.pageX;
        return _this.mouseY = e.pageY;
      });
    }

    Ipl6.prototype.update = function(e) {
      return this.$container.css('-webkit-transform', 'rotateY(' + this.maxXRot * this.mouseDistFromCenterX() / 1000 + 'deg) rotateX(' + this.maxYRot * -this.mouseDistFromCenterY() / 1000 + 'deg)');
    };

    Ipl6.prototype.mouseDistFromCenterX = function() {
      return this.mouseX - (this.$container.offset().left + this.$container.outerWidth() * .5);
    };

    Ipl6.prototype.mouseDistFromCenterY = function() {
      return this.mouseY - (this.$container.offset().top - 100 + this.$container.outerHeight() * .5);
    };

    return Ipl6;

  })();

}).call(this);
