// Generated by CoffeeScript 1.3.3
(function() {

  $('a.sponsor-scroll').click(function() {
    var $actGive, newTop;
    $actGive = $('div.active-giveaway');
    newTop = ($actGive.offset().top + ($actGive.outerHeight() * .5)) - ($(window).height() * .5);
    $('html,body').animate({
      'scrollTop': newTop
    }, {
      'queue': false,
      'duration': 300
    });
    return false;
  });

}).call(this);
