// Generated by CoffeeScript 1.3.3
(function() {

  window.initialLoadDisqus = function(franchiseSlug) {
    var DISQUSINT, counter, disqus_shortname, dsq;
    disqus_shortname = 'ipl-events';
    dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    counter = 0;
    return DISQUSINT = setInterval(function() {
      counter += 1;
      if (typeof DISQUS === "object" && (typeof DISQUS !== "undefined" && DISQUS !== null ? DISQUS.reset : void 0) || counter === 20) {
        if (counter !== 20) {
          DISQUS.reset({
            reload: true,
            config: function() {
              this.page.identifier = "" + franchiseSlug + " comments";
              return this.page.url = "" + document.location.href + "#!" + franchiseSlug;
            }
          });
        }
        return clearInterval(DISQUSINT);
      }
    }, 50);
  };

  window.loadDisqus = function(franchiseSlug) {
    return DISQUS.reset({
      reload: true,
      config: function() {
        this.page.identifier = "" + franchiseSlug + " comments";
        return this.page.url = "http://esports.ign.com/vote/v1/widget#!" + franchiseSlug;
      }
    });
  };

}).call(this);
